n1:
	gcc -o prog -g main1.c kahoot.c

n2:
	gcc -o prog -g main2.c kahoot.c listElem.c listArrayList.c utils.c

n3:
	gcc -o prog -g main3.c kahoot.c listElem.c listArrayList.c utils.c

run:
	./prog

clean:
	rm -f prog*
